name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Node Packages
        run: yarn install --immutable --immutable-cache

      - name: Lint App
        run: yarn run lint:app

      - name: Build Peer Party
        run: yarn run build:peer-party

      - name: Run Tests
        run: yarn run test:unit

      - name: Build Storybook
        run: yarn run build:storybook

      - name: Build App
        run: yarn run build:app

      - name: Build Docs
        run: yarn run build:docs

      - name: Deploy App
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./app/build
          cname: www.compendium.games

      - name: Deploy Storybook
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./app/storybook-static
          destination_dir: storybook

      - name: Deploy Documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./peer-party/docs
          destination_dir: docs



      


